### ISSUE TITLE
오늘 업데이트 이후 로그인이 안됩니다.

### ISSUE THREAD

**Issue by DopingDeveloper** [lunDreame/homeassistant-apti#6]
로거: homeassistant.config_entries
소스: config_entries.py:594
처음 발생: 오전 10:22:21 (1 발생)
마지막 로그인: 오전 10:22:21
```
Error setting up entry <phone number> for apti
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apti/__init__.py", line 17, in async_setup_entry
    await coordinator.api.login()
  File "/config/custom_components/apti/apti.py", line 92, in login
    if not is_phone_number(self.id):
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apti/helper.py", line 36, in is_phone_number
    return bool(re.match(phone_number_pattern, id_value))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/re/__init__.py", line 167, in match
    return _compile(pattern, flags).match(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by lunDreame** [comment]
1.0.4 버전에서 문제가 해결되었습니다!
